using Godot;
using System;

public partial class Spawner : Node2D
{
	[Export]
	public PackedScene entityScene;
	[Export]
	public int entityNumLimit = 5;

	private float SPAWN_INTERVAL = 5f;

	private float spawnCooldown = 0f;

	// All entities generated by the spawner will be added as a child 
	private int getCurrentEntityNum(){
		return this.GetChildren().Count;
	}
	
	public override void _Process(double delta)
	{
		if (getCurrentEntityNum() < entityNumLimit)
		{
			spawnCooldown -= (float)delta;
			if (spawnCooldown <= 0)
			{
				var randomOffset = new Vector2(GD.RandRange(-50, 50), GD.RandRange(-50, 50));
				string entityName = GD.Randf() < 0.5f ? "Zombie" : "Skeleton";
				GameScene.SpawnEntity(entityName, GlobalPosition + randomOffset);
				spawnCooldown = SPAWN_INTERVAL;
			}
		}
	}

}
